[unstable]
build-std-features =  ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "target.json"

[target.'cfg(target_os = "none")']
#runner = "qemu-system-x86_64"
runner =  "bootimage runner"
